// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/27/2025, 10:08:30 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["F:/Projects/NUXT3/nuxt-tailwind-auth/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Projects/NUXT3/nuxt-tailwind-auth/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Projects/NUXT3/nuxt-tailwind-auth/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Projects/NUXT3/nuxt-tailwind-auth/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Projects/NUXT3/nuxt-tailwind-auth/app/plugins/**/*.{js,ts,mjs}","F:/Projects/NUXT3/nuxt-tailwind-auth/app/composables/**/*.{js,ts,mjs}","F:/Projects/NUXT3/nuxt-tailwind-auth/app/utils/**/*.{js,ts,mjs}","F:/Projects/NUXT3/nuxt-tailwind-auth/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","F:/Projects/NUXT3/nuxt-tailwind-auth/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","F:/Projects/NUXT3/nuxt-tailwind-auth/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","F:/Projects/NUXT3/nuxt-tailwind-auth/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;